# Generated by Django 4.0 on 2022-05-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_rename_user_message_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='color',
            field=models.CharField(default='red', max_length=255),
        ),
    ]
